### ISSUE TITLE
Missing syntax: props punning, optional props

### ISSUE THREAD

**Issue by jchavarri** [andreypopp/mlx#2]
For both props:

```diff
- <input onChange=onChange />
+ <input onChange />
```

and optional arg syntax `?value=value` and `?value`.

**Comment by andreypopp** [comment]
Hm... props punning actually works already but `ocamlformat-mlx` needs to reformat where appropriate.

**Comment by jchavarri** [comment]
Ahh yes, I think I have not started testing `ocamlformat-mlx` yet.

**Comment by andreypopp** [comment]
Added reformat for punning where possible in ocamlformat-mlx.0.2. Will keep this issue open for support for `?prop` syntax.

**Comment by andreypopp** [comment]
Fixed in 3d0c49c97bacd03d5eca2497676fcac100936c2e, release as 0.4 (ocamlformat-mlx support as well).

**Comment by jchavarri** [comment]
thanks!
